#!/bin/sh
# shellcheck disable=SC2039
ast_ver_short=$(asterisk -V | cut -d '.' -f1 | cut -d ' ' -f2)
local location="$1"
/etc/init.d/asterisk stop
/etc/init.d/asterisk disable

opkg remove --autoremove --force-depends --force-removal-of-dependent-packages asterisk"${ast_ver_short}"*
asterisk -V && opkg remove --force-remove asterisk"${ast_ver_short}"

rm -rf /etc/asterisk
rm -rf /usr/lib/asterisk
rm -rf /usr/share/asterisk
rm /etc/init.d/asterisk

if [[ -f /etc/config/mmpbxrvsipnet.orig ]]; then
	cp /etc/config/mmpbxrvsipnet.orig /etc/config/mmpbxrvsipnet &&
	rm /etc/config/mmpbxrvsipnet.orig
fi
uci set modgui.app.blacklist_app='0'
uci commit
/etc/init.d/mmpbxd restart
[[ -d "$location" && "$BKL_KEEP_LOCATION" -eq 1 ]] && rm -r "$location"
rm /usr/bin/blacklist
